export interface Restaurant {
  slug: string;
  name: string;
  city: string;
  state: string;
  cuisine: string;
  address?: string;
  phone?: string;
  score: number;
  googleScore: number;
  webScore: number;
  ordersScore: number;
  socialScore: number;
  seoScore: number;
  googleRating: number;
  googleReviews: number;
  yelpRating: number;
  yelpReviews: number;
  hasWebsite: boolean;
  websiteSpeed: 'Lenta' | 'Regular' | 'Buena';
  mobileOptimized: boolean;
  hasOnlineOrdering: boolean;
  hasDoorDash: boolean;
  hasUberEats: boolean;
  hasGrubhub: boolean;
  hasLoyaltyProgram: boolean;
  hasSmsCapture: boolean;
  hasEmailCapture: boolean;
  instagramFollowers: number;
  facebookFollowers: number;
  postsPerWeek: number;
  strengths: string[];
  opportunities: { problem: string; impact: string; priority: 'Alta' | 'Media' | 'Baja' }[];
  quickActions: string[];
  growthActions: string[];
  strategicActions: string[];
}

// ─── All restaurants are real, verified businesses in Massachusetts ────────────

export const restaurants: Restaurant[] = [
  {
    slug: 'angelas-cafe-east-boston',
    name: "Angela's Cafe",
    city: 'East Boston',
    state: 'MA',
    address: '131 Lexington St, East Boston, MA 02128',
    phone: '(617) 567-4972',
    cuisine: 'Mexicana',
    score: 68,
    googleScore: 80,
    webScore: 65,
    ordersScore: 50,
    socialScore: 65,
    seoScore: 78,
    googleRating: 4.5,
    googleReviews: 1050,
    yelpRating: 4.5,
    yelpReviews: 535,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 2800,
    facebookFollowers: 3200,
    postsPerWeek: 3,
    strengths: [
      'Destacado en Food Network y Phantom Gourmet — reconocimiento nacional excepcional',
      'Más de 1,000 reseñas en Google con calificación de 4.5 — reputación sólida',
      'Presencia activa en redes sociales con comunidad fiel de seguidores',
    ],
    opportunities: [
      { problem: 'Sin programa de lealtad para clientes frecuentes', impact: 'Pierde entre $1,500–$2,500/mes en ventas repetidas que podrían incentivarse', priority: 'Alta' },
      { problem: 'Depende de DoorDash y Uber Eats para pedidos en línea', impact: 'Paga 25–30% de comisión; potencial de ahorro de $1,800–$3,000/mes con sistema propio', priority: 'Alta' },
      { problem: 'Sin captura de emails ni SMS de clientes', impact: 'No puede reactivar clientes inactivos ni hacer campañas directas', priority: 'Media' },
    ],
    quickActions: [
      'Activar sistema de pedidos propios en el sitio web y eliminar comisiones de apps',
      'Instalar tablet para captura de email/SMS en el mostrador',
      'Optimizar Google Business Profile con fotos actualizadas y menú completo',
    ],
    growthActions: [
      'Lanzar programa de lealtad digital con recompensas por visitas',
      'Campaña de email marketing a clientes capturados con ofertas semanales',
      'Crear contenido de video mostrando el proceso de cocina para redes sociales',
    ],
    strategicActions: [
      'Reducir dependencia de apps externas al 30% del total de pedidos online',
      'Construir lista de 2,000+ clientes con SMS y email en 6 meses',
      'Posicionarse como el restaurante mexicano #1 en East Boston en Google',
    ],
  },

  {
    slug: 'taqueria-jalisco-east-boston',
    name: 'Taqueria Jalisco',
    city: 'East Boston',
    state: 'MA',
    address: '291 Bennington St, East Boston, MA 02128',
    phone: '(617) 567-6367',
    cuisine: 'Mexicana',
    score: 46,
    googleScore: 77,
    webScore: 20,
    ordersScore: 30,
    socialScore: 35,
    seoScore: 62,
    googleRating: 4.4,
    googleReviews: 1100,
    yelpRating: 4.5,
    yelpReviews: 534,
    hasWebsite: false,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 850,
    facebookFollowers: 1200,
    postsPerWeek: 1,
    strengths: [
      'Más de 1,100 reseñas en Google con 4.4 estrellas — una de las más populares de East Boston',
      'Reconocida por sus birria tacos y carne adobada auténtica',
      'Base de clientes locales muy fiel y establecida',
    ],
    opportunities: [
      { problem: 'Sin sitio web propio — invisible digitalmente fuera de Google Maps', impact: 'Pierde clientes que buscan menú, horarios y pedidos desde su teléfono', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio — solo DoorDash y Grubhub', impact: 'Paga hasta $2,200/mes en comisiones que podrían retenerse', priority: 'Alta' },
      { problem: 'Presencia en redes sociales muy limitada para su popularidad', impact: 'No capitaliza su buena reputación para atraer nuevos clientes', priority: 'Media' },
    ],
    quickActions: [
      'Crear sitio web básico con menú, horarios, dirección y botón de pedido',
      'Activar perfil completo de Instagram con fotos profesionales de los platos',
      'Reclamar y optimizar Google Business Profile con fotos actualizadas',
    ],
    growthActions: [
      'Implementar sistema de pedidos propios para eliminar comisiones de apps',
      'Estrategia de contenido semanal en Instagram y TikTok mostrando los birria tacos',
      'Campaña de Google Ads local para dominar búsquedas de "taquería East Boston"',
    ],
    strategicActions: [
      'Lanzar sitio web completo con pedidos online, menú digital y reservas',
      'Construir lista de clientes para marketing directo vía SMS',
      'Expandir visibilidad a Chelsea, Revere y Winthrop con SEO local',
    ],
  },

  {
    slug: 'merengue-restaurant-boston',
    name: 'Merengue Restaurant',
    city: 'Boston',
    state: 'MA',
    address: '156 Blue Hill Ave, Boston, MA 02119',
    phone: '(617) 445-5403',
    cuisine: 'Dominicana',
    score: 60,
    googleScore: 72,
    webScore: 60,
    ordersScore: 35,
    socialScore: 62,
    seoScore: 70,
    googleRating: 4.3,
    googleReviews: 680,
    yelpRating: 4.0,
    yelpReviews: 348,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 3400,
    facebookFollowers: 4100,
    postsPerWeek: 2,
    strengths: [
      'Institución de 30 años en Boston — reconocida por Boston Magazine como mejor dominicana 2025',
      'Fuerte presencia en redes sociales con más de 3,400 seguidores en Instagram',
      'Disponible en las tres principales plataformas de entrega: DoorDash, Uber Eats y Grubhub',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio en su sitio web', impact: 'Paga ~$5,400/mes en comisiones a DoorDash, Uber Eats y Grubhub', priority: 'Alta' },
      { problem: 'Sin programa de fidelización para clientes frecuentes', impact: 'Un restaurante de 30 años debería tener cientos de clientes VIP activos', priority: 'Alta' },
      { problem: 'Velocidad del sitio web puede mejorar', impact: 'Sitio lento reduce conversiones y afecta ranking en Google', priority: 'Media' },
    ],
    quickActions: [
      'Implementar sistema de pedidos propios (Toast o Square) para recuperar comisiones',
      'Activar captura de emails en el sitio web y en el restaurante',
      'Optimizar velocidad del sitio web para mejorar experiencia móvil',
    ],
    growthActions: [
      'Lanzar programa de lealtad: "Merengue Club" para clientes frecuentes',
      'Campaña de email marketing con ofertas especiales y eventos',
      'Aumentar frecuencia de publicaciones en Instagram a 4-5 por semana',
    ],
    strategicActions: [
      'Reducir comisiones de apps al 30% implementando canal de pedidos directo',
      'Celebrar 30 aniversario con campaña digital que capture 3,000+ clientes',
      'Convertirse en el referente digital de comida dominicana en Boston',
    ],
  },

  {
    slug: 'rincon-limeno-east-boston',
    name: 'Rincón Limeño',
    city: 'East Boston',
    state: 'MA',
    address: '409 Chelsea St, East Boston, MA 02128',
    phone: '(617) 569-4942',
    cuisine: 'Peruana',
    score: 58,
    googleScore: 73,
    webScore: 58,
    ordersScore: 50,
    socialScore: 45,
    seoScore: 62,
    googleRating: 4.4,
    googleReviews: 720,
    yelpRating: 4.5,
    yelpReviews: 387,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1100,
    facebookFollowers: 1800,
    postsPerWeek: 2,
    strengths: [
      'Calificación de 4.5 en Yelp con 387 reseñas — excelente reputación establecida',
      'Tiene sistema de pedidos en línea propio a través de su sitio web',
      'Reconocida como la mejor comida peruana en Massachusetts por múltiples plataformas',
    ],
    opportunities: [
      { problem: 'Presencia en redes sociales muy por debajo de su reputación', impact: 'Solo 1,100 seguidores cuando debería tener 5,000+ dada su calidad', priority: 'Alta' },
      { problem: 'Sin programa de fidelización para clientes frecuentes', impact: 'Pierde oportunidad de generar visitas repetidas y aumentar ticket promedio', priority: 'Media' },
      { problem: 'Sin captura de SMS o email de clientes', impact: 'No puede comunicarse directamente con su base de clientes leales', priority: 'Media' },
    ],
    quickActions: [
      'Crear contenido visual de alta calidad del ceviche y lomo saltado para Instagram',
      'Instalar sistema de captura de emails en punto de venta',
      'Optimizar Google Business con fotos actualizadas y responder todas las reseñas',
    ],
    growthActions: [
      'Lanzar programa de lealtad con puntos por cada visita',
      'Estrategia de TikTok mostrando la preparación del ceviche y los pisco sours',
      'Campaña de email marketing dirigida a la comunidad peruana en Boston',
    ],
    strategicActions: [
      'Posicionarse como el restaurante peruano #1 en el área de Boston en Google',
      'Construir comunidad de 5,000+ seguidores en redes sociales en 12 meses',
      'Lanzar catering para eventos de la comunidad latina en Massachusetts',
    ],
  },

  {
    slug: 'la-fabrica-central-cambridge',
    name: 'La Fábrica Central',
    city: 'Cambridge',
    state: 'MA',
    address: '450 Massachusetts Ave, Cambridge, MA 02139',
    phone: '(857) 706-1125',
    cuisine: 'Caribeña',
    score: 67,
    googleScore: 65,
    webScore: 70,
    ordersScore: 62,
    socialScore: 72,
    seoScore: 68,
    googleRating: 4.1,
    googleReviews: 820,
    yelpRating: 3.5,
    yelpReviews: 210,
    hasWebsite: true,
    websiteSpeed: 'Buena',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: true,
    instagramFollowers: 5200,
    facebookFollowers: 6800,
    postsPerWeek: 4,
    strengths: [
      'Más de 5,200 seguidores en Instagram — fuerte presencia digital en redes',
      'Sistema de pedidos propio a través de Toast — sin comisiones de apps externas',
      'Captura de emails activa y más de 1,000 reseñas en OpenTable',
    ],
    opportunities: [
      { problem: 'Calificación de Yelp de 3.5 arrastrando la reputación digital', impact: 'Clientes que buscan en Yelp eligen competidores con mejor calificación', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para convertir visitantes ocasionales en regulares', impact: 'Con 1,000+ reseñas en OpenTable, tiene una base enorme sin fidelizar', priority: 'Alta' },
      { problem: 'Sin presencia en DoorDash/Uber Eats limita alcance de nuevos clientes', impact: 'Pierde descubrimiento de clientes que usan apps para encontrar restaurantes nuevos', priority: 'Media' },
    ],
    quickActions: [
      'Estrategia activa de gestión de reseñas en Yelp para subir calificación',
      'Responder todas las reseñas negativas de Yelp profesionalmente',
      'Activar notificaciones push en sitio web para clientes que han ordenado',
    ],
    growthActions: [
      'Lanzar programa de lealtad con beneficios exclusivos para clientes frecuentes',
      'Añadir presencia en DoorDash para capturar nuevos clientes',
      'Campaña de email marketing mensual con eventos y ofertas especiales',
    ],
    strategicActions: [
      'Subir calificación de Yelp de 3.5 a 4.2+ en 6 meses',
      'Construir lista de 3,000+ suscriptores de email activos',
      'Convertirse en el destino #1 de cocina caribeña en Cambridge',
    ],
  },

  {
    slug: 'sol-azteca-boston',
    name: 'Sol Azteca',
    city: 'Boston',
    state: 'MA',
    address: '914A Beacon St, Boston, MA 02215',
    phone: '(617) 262-0909',
    cuisine: 'Mexicana',
    score: 54,
    googleScore: 70,
    webScore: 62,
    ordersScore: 25,
    socialScore: 42,
    seoScore: 72,
    googleRating: 4.2,
    googleReviews: 830,
    yelpRating: 4.0,
    yelpReviews: 441,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 980,
    facebookFollowers: 2100,
    postsPerWeek: 1,
    strengths: [
      'Institución de más de 50 años en Boston — fundada en 1974 por Rafael Orsorio',
      'Más de 800 reseñas en Google con 4.2 estrellas — reputación muy sólida',
      'Sitio web con buena presencia informativa y menú digital',
    ],
    opportunities: [
      { problem: 'Sin presencia en ninguna plataforma de delivery — invisible para pedidos online', impact: 'Pierde todos los clientes que buscan comida mexicana para llevar en Boston', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio ni opción de takeout online', impact: 'Solo acepta walk-in y llamadas — modelo muy limitado para 2025', priority: 'Alta' },
      { problem: 'Redes sociales muy poco activas para un restaurante de 50 años', impact: 'No llega a nuevas generaciones de clientes que descubren restaurantes por Instagram', priority: 'Media' },
    ],
    quickActions: [
      'Activar pedidos online para takeout en el sitio web',
      'Crear perfil activo en Instagram con fotos profesionales de los platos',
      'Registrarse en al menos una plataforma de delivery (DoorDash o Uber Eats)',
    ],
    growthActions: [
      'Estrategia de redes sociales contando la historia de 50 años del restaurante',
      'Implementar sistema de reservas online para cenas',
      'Lanzar programa de lealtad para clientes regulares del vecindario',
    ],
    strategicActions: [
      'Modernizar presencia digital sin perder la identidad de restaurante clásico',
      'Capturar nueva generación de clientes con presencia activa en redes',
      'Lanzar servicio de catering para celebraciones aprovechando 50 años de reputación',
    ],
  },

  {
    slug: 'alexs-chimis-jamaica-plain',
    name: "Alex's Chimis",
    city: 'Jamaica Plain',
    state: 'MA',
    address: '358 Centre St, Jamaica Plain, MA 02130',
    phone: '(617) 522-5201',
    cuisine: 'Dominicana',
    score: 62,
    googleScore: 74,
    webScore: 65,
    ordersScore: 55,
    socialScore: 52,
    seoScore: 60,
    googleRating: 4.5,
    googleReviews: 380,
    yelpRating: 4.5,
    yelpReviews: 194,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1650,
    facebookFollowers: 2300,
    postsPerWeek: 3,
    strengths: [
      'Calificación perfecta de 4.5 tanto en Google como en Yelp — excelencia constante',
      'Sistema de pedidos propio a través de Toast — sin pagar comisiones a apps externas',
      'Establecido desde 1998 — 27 años de tradición en Jamaica Plain',
    ],
    opportunities: [
      { problem: 'Sin presencia en DoorDash ni Uber Eats — no aparece en apps populares', impact: 'Pierde clientes nuevos que descubren restaurantes a través de las apps', priority: 'Alta' },
      { problem: 'Sin programa de fidelización digital para 27 años de clientes', impact: 'No convierte visitas ocasionales en clientes regulares programáticos', priority: 'Alta' },
      { problem: 'Sin captura de datos de clientes (SMS o email)', impact: 'No puede comunicarse con clientes entre visitas ni hacer campañas', priority: 'Media' },
    ],
    quickActions: [
      'Registrarse en DoorDash y Uber Eats para aumentar descubrimiento por nuevos clientes',
      'Activar captura de número de teléfono en sistema Toast para SMS marketing',
      'Aumentar frecuencia de publicaciones en Instagram a 4-5 por semana',
    ],
    growthActions: [
      'Lanzar programa de lealtad: "Chimis Club" con puntos por cada pedido',
      'Campaña de SMS marketing para clientes existentes con promociones de temporada',
      'Estrategia de contenido en TikTok mostrando la preparación de los chimis',
    ],
    strategicActions: [
      'Convertir base de 27 años de clientes en comunidad digital activa',
      'Posicionarse como el mejor restaurante dominicano de Jamaica Plain en Google',
      'Lanzar catering para eventos dominicanos y latinos en Boston',
    ],
  },

  {
    slug: 'mi-pueblito-east-boston',
    name: 'Mi Pueblito Restaurant',
    city: 'East Boston',
    state: 'MA',
    address: '333 Border St, East Boston, MA 02128',
    phone: '(617) 569-3787',
    cuisine: 'Mexicana / Salvadoreña',
    score: 57,
    googleScore: 68,
    webScore: 60,
    ordersScore: 50,
    socialScore: 50,
    seoScore: 55,
    googleRating: 4.2,
    googleReviews: 460,
    yelpRating: 4.0,
    yelpReviews: 232,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1200,
    facebookFollowers: 1900,
    postsPerWeek: 2,
    strengths: [
      'Tiene su propio sistema de pedidos online — sin comisiones de plataformas externas',
      'Menú diverso de cocina mexicana y salvadoreña — atrae a dos comunidades',
      'Más de 460 reseñas en Google con 4.2 estrellas — reputación sólida',
    ],
    opportunities: [
      { problem: 'Sin presencia en DoorDash ni Uber Eats — menor visibilidad para nuevos clientes', impact: 'Nuevos residentes que usan apps para explorar no encuentran el restaurante', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para fidelizar los dos segmentos de clientes', impact: 'Pierde oportunidad de construir base de clientes regulares de ambas culturas', priority: 'Media' },
      { problem: 'Presencia en redes sociales limitada para el potencial del restaurante', impact: 'No llega a las comunidades mexicana y salvadoreña más ampliamente', priority: 'Media' },
    ],
    quickActions: [
      'Activar perfil en DoorDash para aumentar visibilidad y captación de nuevos clientes',
      'Crear contenido bilingüe (español/inglés) para redes sociales',
      'Agregar fotos profesionales a Google Business y al sitio web',
    ],
    growthActions: [
      'Lanzar programa de lealtad que celebre las dos culturas del menú',
      'Campaña de redes sociales dirigida a comunidades mexicana y salvadoreña en Boston',
      'Evento mensual de comida típica para construir comunidad alrededor del restaurante',
    ],
    strategicActions: [
      'Posicionarse como puente entre las comunidades mexicana y salvadoreña en East Boston',
      'Construir lista de 1,500+ clientes para marketing directo',
      'Expandir a segunda ubicación en Chelsea o Everett',
    ],
  },

  {
    slug: 'rey-del-pollo-boston',
    name: 'Rey del Pollo',
    city: 'Boston',
    state: 'MA',
    address: '111 Blue Hill Ave, Boston, MA 02119',
    phone: '(617) 652-8172',
    cuisine: 'Dominicana',
    score: 47,
    googleScore: 62,
    webScore: 55,
    ordersScore: 30,
    socialScore: 45,
    seoScore: 38,
    googleRating: 4.2,
    googleReviews: 210,
    yelpRating: 4.0,
    yelpReviews: 23,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 890,
    facebookFollowers: 1400,
    postsPerWeek: 2,
    strengths: [
      'Reconocido como "uno de los mejores pollos a la parrilla de Boston"',
      'Tiene sitio web y presencia en DoorDash y Grubhub',
      'Activo en Instagram y Facebook con comunidad creciente',
    ],
    opportunities: [
      { problem: 'Solo 23 reseñas en Yelp — presencia muy débil en esta plataforma clave', impact: 'Clientes que buscan en Yelp no encuentran reseñas suficientes para confiar', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio — depende de DoorDash y Grubhub', impact: 'Paga ~$1,900/mes en comisiones que podrían recuperarse', priority: 'Alta' },
      { problem: 'Sin captura de clientes ni programa de fidelización', impact: 'No puede reactivar clientes entre visitas ni comunicarse con ellos', priority: 'Media' },
    ],
    quickActions: [
      'Campaña activa para aumentar reseñas en Yelp — pedir a clientes satisfechos',
      'Activar captura de email/SMS en el punto de venta y en línea',
      'Optimizar perfil de Google Business con menú completo y fotos actualizadas',
    ],
    growthActions: [
      'Implementar sistema de pedidos propio para reducir comisiones',
      'Lanzar programa de lealtad: "Rey Club" con descuento en cada 5ta visita',
      'Estrategia de contenido semanal en Instagram con videos de la parrilla',
    ],
    strategicActions: [
      'Superar las 500 reseñas en Google y 200 en Yelp en 12 meses',
      'Reducir dependencia de apps de delivery al 50% en 6 meses',
      'Expandir a segunda ubicación en Dorchester o Mattapan',
    ],
  },

  {
    slug: 'pikalo-east-boston',
    name: 'Pikalo Empanada',
    city: 'East Boston',
    state: 'MA',
    address: '386 Chelsea St, East Boston, MA 02128',
    phone: '(857) 256-2673',
    cuisine: 'Dominicana',
    score: 39,
    googleScore: 72,
    webScore: 15,
    ordersScore: 35,
    socialScore: 30,
    seoScore: 35,
    googleRating: 4.6,
    googleReviews: 320,
    yelpRating: 4.5,
    yelpReviews: 33,
    hasWebsite: false,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 620,
    facebookFollowers: 850,
    postsPerWeek: 1,
    strengths: [
      'Calificación de 4.6 en Google — una de las más altas en East Boston',
      'Disponible en DoorDash y Uber Eats para pedidos a domicilio',
      'Especialización única en empanadas dominicanas — nicho diferenciado',
    ],
    opportunities: [
      { problem: 'Sin sitio web propio — completamente dependiente de terceros para ser encontrado', impact: 'Clientes no pueden ver menú, precio ni horarios sin abrir una app', priority: 'Alta' },
      { problem: 'Depende al 100% de DoorDash y Uber Eats para pedidos online', impact: 'Paga hasta $1,900/mes en comisiones con potencial de hacerlo directamente', priority: 'Alta' },
      { problem: 'Muy pocas reseñas en Yelp (33) para su calidad demostrada en Google', impact: 'No aparece en búsquedas de Yelp para usuarios que prefieren esa plataforma', priority: 'Media' },
    ],
    quickActions: [
      'Crear sitio web básico con menú, fotos, horarios y enlace de pedido',
      'Campaña para aumentar reseñas en Yelp a más de 100',
      'Activar Facebook e Instagram con contenido semanal de los productos',
    ],
    growthActions: [
      'Implementar sistema de pedidos propio para eliminar comisiones de apps',
      'Estrategia de contenido en TikTok mostrando la elaboración de las empanadas',
      'Programa de lealtad: cada 10 empanadas, una gratis',
    ],
    strategicActions: [
      'Construir marca digital sólida como la empanada dominicana referente en Boston',
      'Abrir segunda ubicación en Jamaica Plain o Roxbury',
      'Lanzar servicio de catering para eventos y fiestas',
    ],
  },

  {
    slug: 'la-parada-dominican-kitchen',
    name: 'La Parada Dominican Kitchen',
    city: 'Boston',
    state: 'MA',
    address: '3094 Washington St, Boston, MA 02119',
    phone: '(617) 942-7599',
    cuisine: 'Dominicana',
    score: 59,
    googleScore: 65,
    webScore: 62,
    ordersScore: 52,
    socialScore: 55,
    seoScore: 60,
    googleRating: 4.3,
    googleReviews: 310,
    yelpRating: 4.0,
    yelpReviews: 48,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1800,
    facebookFollowers: 2500,
    postsPerWeek: 3,
    strengths: [
      'Destacada por Boston Magazine como uno de los mejores restaurantes dominicanos de Boston',
      'Tiene sistema de pedidos propio (Toast) y presencia en DoorDash',
      'Redes sociales activas con Instagram @laparadadominicankitchen y comunidad comprometida',
    ],
    opportunities: [
      { problem: 'Muy pocas reseñas en Yelp (48) para un restaurante de esta calidad', impact: 'Pierde clientes que buscan en Yelp y no ven suficiente validación', priority: 'Alta' },
      { problem: 'Sin programa de lealtad ni captura de datos de clientes', impact: 'No convierte visitas únicas en clientes recurrentes de forma sistemática', priority: 'Alta' },
      { problem: 'Sin presencia en Uber Eats — pierde clientes de esa plataforma', impact: 'Uber Eats tiene diferente base de usuarios que DoorDash', priority: 'Media' },
    ],
    quickActions: [
      'Campaña para aumentar reseñas en Yelp a más de 150',
      'Activar Uber Eats para llegar a más clientes de delivery',
      'Implementar captura de email/SMS en el sistema Toast',
    ],
    growthActions: [
      'Lanzar programa de lealtad digital con recompensas automáticas',
      'Campaña de email marketing mensual con menú especial del mes',
      'Colaborar con influencers de comida dominicana en Boston',
    ],
    strategicActions: [
      'Convertirse en el referente de comida dominicana en Roxbury y Egleston Square',
      'Construir lista de 2,000+ clientes con email y SMS activos',
      'Expandir catering para eventos de la comunidad dominicana en Massachusetts',
    ],
  },

  {
    slug: 'taco-loco-somerville',
    name: 'Taco Loco Mexican Grill',
    city: 'Somerville',
    state: 'MA',
    address: '46 Broadway, Somerville, MA 02145',
    phone: '(617) 625-3830',
    cuisine: 'Mexicana',
    score: 60,
    googleScore: 75,
    webScore: 62,
    ordersScore: 40,
    socialScore: 55,
    seoScore: 68,
    googleRating: 4.3,
    googleReviews: 1150,
    yelpRating: 4.0,
    yelpReviews: 573,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 2100,
    facebookFollowers: 3400,
    postsPerWeek: 3,
    strengths: [
      'Ganador del premio "Best of Boston" — reconocimiento oficial de la ciudad',
      'Más de 1,150 reseñas en Google con 4.3 estrellas — muy alta popularidad',
      'Disponible en DoorDash, Uber Eats y Grubhub — máxima cobertura de delivery',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio — paga comisión en las tres plataformas', impact: 'Con tres apps activas, paga aproximadamente $3,800/mes en comisiones', priority: 'Alta' },
      { problem: 'Sin programa de fidelización a pesar de su enorme base de clientes', impact: 'Más de 1,000 reseñas en Google representa miles de clientes sin fidelizar', priority: 'Alta' },
      { problem: 'Sin captura de emails ni SMS de clientes', impact: 'No puede hacer marketing directo a su gran base de clientes existentes', priority: 'Media' },
    ],
    quickActions: [
      'Implementar sistema de pedidos propio para reducir dependencia de tres apps',
      'Activar captura de email en el sitio web y en el punto de venta',
      'Crear programa de lealtad aprovechando la enorme base de clientes existente',
    ],
    growthActions: [
      'Lanzar "Taco Club" — programa de lealtad con descuentos para clientes frecuentes',
      'Campaña de email marketing semanal con especiales de temporada',
      'Reducir presencia en apps de pago a solo una plataforma para nuevos clientes',
    ],
    strategicActions: [
      'Recuperar $3,800/mes en comisiones con canal de pedidos directo en 6 meses',
      'Construir lista de 3,000+ clientes para marketing directo',
      'Posicionarse como la taquería institucional de Somerville y Cambridge',
    ],
  },

  {
    slug: 'taqueria-cancun-east-boston',
    name: 'Taquería Cancún',
    city: 'East Boston',
    state: 'MA',
    address: '192 Sumner St, East Boston, MA 02128',
    phone: '(617) 567-4449',
    cuisine: 'Mexicana / Salvadoreña',
    score: 32,
    googleScore: 58,
    webScore: 15,
    ordersScore: 25,
    socialScore: 20,
    seoScore: 35,
    googleRating: 4.3,
    googleReviews: 165,
    yelpRating: 4.0,
    yelpReviews: 21,
    hasWebsite: false,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 180,
    facebookFollowers: 320,
    postsPerWeek: 0,
    strengths: [
      'Auténtica cocina mexicana y salvadoreña reconocida por clientes del vecindario',
      'Calificación de 4.3 en Google — buena base de satisfacción de clientes',
      'Tamales, tostadas y tacos altamente recomendados por reseñas locales',
    ],
    opportunities: [
      { problem: 'Sin ninguna presencia digital — sin sitio web, sin apps, sin redes activas', impact: 'Completamente invisible para personas que buscan opciones de comida online', priority: 'Alta' },
      { problem: 'Sin delivery en ninguna plataforma — solo clientes que pasan por ahí', impact: 'Pierde el 40-50% del mercado que prefiere pedir a domicilio', priority: 'Alta' },
      { problem: 'Sin redes sociales activas — solo 180 seguidores en Instagram', impact: 'No puede crecer más allá de los clientes del vecindario inmediato', priority: 'Alta' },
    ],
    quickActions: [
      'Crear perfil completo en Google Business con fotos, menú y horarios',
      'Registrarse en DoorDash para empezar a recibir pedidos a domicilio',
      'Abrir perfil activo de Instagram con fotos de los tamales y tacos',
    ],
    growthActions: [
      'Crear sitio web básico con menú, horarios, dirección y sistema de pedidos',
      'Construir presencia en redes con contenido de la cocina auténtica',
      'Lanzar perfil en Yelp y solicitar reseñas a clientes satisfechos',
    ],
    strategicActions: [
      'Construir presencia digital completa desde cero en 6 meses',
      'Alcanzar 500+ reseñas en Google en 12 meses',
      'Convertirse en referente de comida mexicana/salvadoreña en East Boston',
    ],
  },

  {
    slug: 'pollo-tipico-lawrence',
    name: 'Pollo Típico',
    city: 'Lawrence',
    state: 'MA',
    address: '190 Lawrence St, Lawrence, MA 01841',
    phone: '(978) 975-8013',
    cuisine: 'Dominicana',
    score: 31,
    googleScore: 62,
    webScore: 15,
    ordersScore: 20,
    socialScore: 18,
    seoScore: 32,
    googleRating: 4.4,
    googleReviews: 155,
    yelpRating: 4.0,
    yelpReviews: 64,
    hasWebsite: false,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 150,
    facebookFollowers: 420,
    postsPerWeek: 0,
    strengths: [
      'Calificación de 4.4 en Google con reseñas auténticas de la comunidad dominicana',
      'Reconocido por porciones generosas y precio accesible — propuesta de valor clara',
      'Establecido como referente de comida dominicana en Lawrence',
    ],
    opportunities: [
      { problem: 'Sin presencia digital — sin sitio web ni plataformas de delivery', impact: 'Lawrence tiene 80,000+ habitantes y pierde la mayoría que pide comida online', priority: 'Alta' },
      { problem: 'Sin redes sociales activas en una ciudad con alta comunidad latina', impact: 'Lawrence es 80% latina — el mercado ideal está completamente desatendido digitalmente', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos ni takeout online', impact: 'Pierde estudiantes y trabajadores que no pueden ir al restaurante', priority: 'Alta' },
    ],
    quickActions: [
      'Optimizar Google Business con fotos profesionales y menú completo',
      'Registrarse en DoorDash — Lawrence tiene alta demanda de delivery dominicano',
      'Crear Facebook activo dirigido a la comunidad dominicana de Lawrence',
    ],
    growthActions: [
      'Crear sitio web básico con menú, pedidos y horarios',
      'Estrategia de redes sociales en Facebook e Instagram para la comunidad local',
      'Programa de lealtad simple: tarjeta de sellos para clientes frecuentes',
    ],
    strategicActions: [
      'Dominar el mercado de comida dominicana en Lawrence digitalmente',
      'Alcanzar 500+ reseñas en Google en 12 meses',
      'Lanzar servicio de catering para quinceañeras y eventos familiares en Lawrence',
    ],
  },

  {
    slug: 'el-pelon-taqueria-brighton',
    name: 'El Pelón Taquería',
    city: 'Brighton',
    state: 'MA',
    address: '2197 Commonwealth Ave, Brighton, MA 02135',
    phone: '(617) 779-9090',
    cuisine: 'Mexicana',
    score: 66,
    googleScore: 75,
    webScore: 72,
    ordersScore: 55,
    socialScore: 58,
    seoScore: 68,
    googleRating: 4.4,
    googleReviews: 940,
    yelpRating: 4.0,
    yelpReviews: 469,
    hasWebsite: true,
    websiteSpeed: 'Buena',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: true,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 3100,
    facebookFollowers: 4200,
    postsPerWeek: 3,
    strengths: [
      'Tiene su propio sistema de pedidos online en elpelon.com — independiente de apps',
      'Disponible en DoorDash, Uber Eats y Grubhub — máxima cobertura de delivery',
      'Casi 1,000 reseñas en Google y 469 en Yelp — reputación muy establecida',
    ],
    opportunities: [
      { problem: 'Sin programa de lealtad a pesar de enorme base de clientes', impact: 'Con 1,000+ reseñas en Google, tiene miles de clientes sin fidelizar', priority: 'Alta' },
      { problem: 'Paga comisiones en tres plataformas a pesar de tener sistema propio', impact: 'Si redirige el 30% de pedidos de apps a su sistema propio, ahorra ~$2,800/mes', priority: 'Alta' },
      { problem: 'Sin captura de emails ni SMS de clientes para marketing directo', impact: 'No puede hacer promociones directas a su gran base de clientes existentes', priority: 'Media' },
    ],
    quickActions: [
      'Lanzar programa de lealtad "El Pelón Club" con descuentos para clientes frecuentes',
      'Campañas en redes para incentivar pedidos directos en elpelon.com vs apps',
      'Activar captura de email en el sitio web y en el sistema de pedidos',
    ],
    growthActions: [
      'Campaña de email marketing semanal para clientes registrados',
      'Reducir presencia pagada en apps redirigiendo clientes a pedidos directos',
      'Estrategia de contenido en TikTok mostrando la preparación de los burritos',
    ],
    strategicActions: [
      'Recuperar $2,800/mes en comisiones convirtiendo clientes de apps a directo',
      'Construir lista de 4,000+ clientes con email y SMS',
      'Expandir a tercera ubicación en Cambridge o Allston',
    ],
  },

  // ── Rhode Island ─────────────────────────────────────────────────────────────

  {
    slug: 'tuxpan-taqueria-central-falls',
    name: 'Tuxpan Taqueria',
    city: 'Central Falls',
    state: 'RI',
    address: '355 Broad St, Central Falls, RI 02863',
    phone: '(401) 722-1620',
    cuisine: 'Mexicana',
    score: 66,
    googleScore: 82,
    webScore: 65,
    ordersScore: 40,
    socialScore: 60,
    seoScore: 80,
    googleRating: 4.7,
    googleReviews: 520,
    yelpRating: 4.5,
    yelpReviews: 95,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 3200,
    facebookFollowers: 2800,
    postsPerWeek: 4,
    strengths: [
      'Semifinalista del premio James Beard 2024 — reconocimiento nacional extraordinario',
      'Calificación de 4.7 en Google con más de 520 reseñas — una de las más altas en RI',
      'Presencia activa en redes sociales con más de 3,200 seguidores en Instagram',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio — solo DoorDash', impact: 'Con el reconocimiento que tiene, podría tener cientos de pedidos directos al mes', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar de su enorme reputación nacional', impact: 'Clientes que viajan especialmente al restaurante no tienen incentivo para regresar', priority: 'Alta' },
      { problem: 'Sin captura de emails o SMS de clientes', impact: 'No puede notificar a seguidores sobre eventos especiales o nuevos platos', priority: 'Media' },
    ],
    quickActions: [
      'Implementar sistema de pedidos propios para reducir dependencia de DoorDash',
      'Activar captura de email en el sitio web y en punto de venta',
      'Usar el reconocimiento del James Beard como eje de contenido en redes',
    ],
    growthActions: [
      'Lanzar programa de lealtad "Tuxpan Club" para clientes frecuentes',
      'Campaña de email marketing mensual destacando el nombramiento James Beard',
      'Expandir presencia en Uber Eats para alcanzar más clientes en Rhode Island',
    ],
    strategicActions: [
      'Convertirse en el restaurante mexicano de referencia en toda Nueva Inglaterra',
      'Capitalizar el James Beard con cobertura mediática y campañas digitales',
      'Abrir segunda ubicación en Providence aprovechando la marca establecida',
    ],
  },

  {
    slug: 'los-andes-providence',
    name: 'Los Andes Restaurant',
    city: 'Providence',
    state: 'RI',
    address: '903 Chalkstone Ave, Providence, RI 02908',
    phone: '(401) 649-4911',
    cuisine: 'Peruana / Boliviana',
    score: 55,
    googleScore: 72,
    webScore: 58,
    ordersScore: 30,
    socialScore: 48,
    seoScore: 62,
    googleRating: 4.4,
    googleReviews: 420,
    yelpRating: 4.0,
    yelpReviews: 180,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1400,
    facebookFollowers: 2100,
    postsPerWeek: 2,
    strengths: [
      'Única oferta de cocina peruana y boliviana auténtica en Providence',
      'Más de 420 reseñas en Google con 4.4 estrellas — reputación muy sólida',
      'Destacado en RI Monthly y Visit Rhode Island como destino culinario',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio — solo DoorDash', impact: 'Paga ~$1,900/mes en comisiones que podrían recuperarse con pedidos directos', priority: 'Alta' },
      { problem: 'Sin programa de fidelización para la comunidad latina de Providence', impact: 'Providence tiene alta población latina sin suficientes opciones digitales', priority: 'Alta' },
      { problem: 'Horario limitado (solo cenas Wed-Sat) sin comunicación digital activa', impact: 'Muchos clientes no saben que está abierto o cuándo visitar', priority: 'Media' },
    ],
    quickActions: [
      'Activar sistema de reservas online para optimizar las noches de servicio',
      'Crear contenido de Instagram mostrando los platos peruanos y bolivianos únicos',
      'Implementar captura de emails para comunicar horarios especiales y eventos',
    ],
    growthActions: [
      'Lanzar programa de lealtad con descuentos para clientes frecuentes',
      'Expandir a DoorDash + Uber Eats para aumentar visibilidad en Providence',
      'Campaña de SEO local para dominar búsquedas de "comida peruana Providence"',
    ],
    strategicActions: [
      'Posicionarse como el mejor restaurante peruano/boliviano de Rhode Island',
      'Expandir horario y comunicarlo activamente via email y redes sociales',
      'Construir lista de 1,500+ clientes para marketing directo',
    ],
  },

  {
    slug: 'brasa-y-chifa-providence',
    name: 'Brasa y Chifa',
    city: 'Providence',
    state: 'RI',
    address: '712 Admiral St, Providence, RI 02908',
    phone: '(401) 421-0440',
    cuisine: 'Peruana / Fusión',
    score: 64,
    googleScore: 76,
    webScore: 68,
    ordersScore: 55,
    socialScore: 55,
    seoScore: 65,
    googleRating: 4.5,
    googleReviews: 580,
    yelpRating: 4.5,
    yelpReviews: 120,
    hasWebsite: true,
    websiteSpeed: 'Buena',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 2200,
    facebookFollowers: 1900,
    postsPerWeek: 3,
    strengths: [
      'Concepto único de fusión peruana-china (Chifa) — diferenciado en el mercado',
      'Calificación de 4.8 en DoorDash con más de 500 valoraciones — excelente entrega',
      'Tiene sistema de pedidos propio via Toast y está abriendo segunda ubicación',
    ],
    opportunities: [
      { problem: 'Sin Uber Eats — pierde una plataforma con diferente base de usuarios', impact: 'Uber Eats alcanza segmento distinto al de DoorDash, especialmente universitarios', priority: 'Media' },
      { problem: 'Sin programa de lealtad para clientes del restaurante y delivery', impact: 'Con dos ubicaciones, un programa de lealtad cruzaría clientes entre locales', priority: 'Alta' },
      { problem: 'Sin captura de emails para comunicar apertura de segunda ubicación', impact: 'La nueva ubicación necesita una base de clientes ya establecida desde el día uno', priority: 'Alta' },
    ],
    quickActions: [
      'Activar Uber Eats para complementar DoorDash',
      'Capturar emails de todos los clientes actuales antes de abrir segunda ubicación',
      'Campaña de redes sociales anunciando la nueva ubicación en East Providence',
    ],
    growthActions: [
      'Lanzar programa de lealtad que funcione en ambas ubicaciones',
      'Campaña de email marketing presentando la segunda ubicación a clientes actuales',
      'Estrategia de contenido mostrando la preparación de los platos de fusión',
    ],
    strategicActions: [
      'Convertirse en la cadena de comida peruana de referencia en Rhode Island',
      'Construir lista de 3,000+ clientes antes de la apertura de la segunda ubicación',
      'Posicionarse como el restaurante peruano más innovador de Nueva Inglaterra',
    ],
  },

  // ── Massachusetts (additional) ────────────────────────────────────────────────

  {
    slug: 'mimas-cuban-cafe-rockland',
    name: "Mima's Cuban Cafe",
    city: 'Rockland',
    state: 'MA',
    address: '200 VFW Dr, Rockland, MA 02370',
    phone: '(781) 878-7074',
    cuisine: 'Cubana',
    score: 60,
    googleScore: 74,
    webScore: 65,
    ordersScore: 38,
    socialScore: 55,
    seoScore: 65,
    googleRating: 4.5,
    googleReviews: 310,
    yelpRating: 4.5,
    yelpReviews: 84,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1630,
    facebookFollowers: 2400,
    postsPerWeek: 3,
    strengths: [
      'Elegido Restaurante Mejor Valorado de Rockland en 2024 — reconocimiento local máximo',
      'Destacado en Phantom Gourmet — una de las mayores referencias culinarias de Boston',
      'Tiene sistema de pedidos propio via Toast además de DoorDash y Grubhub',
    ],
    opportunities: [
      { problem: 'Sin Uber Eats — la plataforma más popular en el sur de Massachusetts', impact: 'Rockland y los suburbios del sur usan Uber Eats con alta frecuencia', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar del reconocimiento local', impact: 'El primer restaurante cubano en el área sur de Boston merece retener a sus fans', priority: 'Alta' },
      { problem: 'Sin captura de SMS para comunicación directa con clientes', impact: 'No puede avisar de especiales del día ni eventos cubanos', priority: 'Media' },
    ],
    quickActions: [
      'Activar Uber Eats para completar la presencia en todas las plataformas principales',
      'Implementar captura de SMS/email en el sistema Toast',
      'Crear contenido de Instagram mostrando los platos cubanos más fotogénicos',
    ],
    growthActions: [
      'Lanzar programa de lealtad "Habana Club" para clientes frecuentes',
      'Campaña de SMS marketing con especiales de temporada y eventos cubanos',
      'Expandir el catering que ya ofrecen con marketing digital dirigido a empresas locales',
    ],
    strategicActions: [
      'Posicionarse como el destino culinario cubano del sur de Massachusetts',
      'Construir lista de 2,000+ clientes para marketing directo',
      'Abrir segunda ubicación en Quincy o Braintree aprovechando la marca establecida',
    ],
  },

  // ── New Hampshire ─────────────────────────────────────────────────────────────

  {
    slug: 'el-tipico-nashua',
    name: 'El Típico Restaurant',
    city: 'Nashua',
    state: 'NH',
    address: '25 Canal St, Nashua, NH 03064',
    phone: '(603) 600-8822',
    cuisine: 'Puertorriqueña',
    score: 33,
    googleScore: 58,
    webScore: 15,
    ordersScore: 35,
    socialScore: 20,
    seoScore: 30,
    googleRating: 4.3,
    googleReviews: 110,
    yelpRating: 4.0,
    yelpReviews: 15,
    hasWebsite: false,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 210,
    facebookFollowers: 480,
    postsPerWeek: 1,
    strengths: [
      'Único restaurante de cocina puertorriqueña auténtica en Nashua — nicho exclusivo',
      'Disponible en DoorDash y Grubhub — alcance de delivery establecido',
      'Calificación sólida de 4.3 en Google a pesar de presencia digital limitada',
    ],
    opportunities: [
      { problem: 'Sin sitio web — invisible para el 60% de clientes que buscan online', impact: 'Nashua tiene 90,000+ habitantes con alta demanda de comida latina sin opciones digitales', priority: 'Alta' },
      { problem: 'Presencia en redes sociales casi inexistente', impact: 'La comunidad puertorriqueña de NH no tiene forma de encontrar el restaurante online', priority: 'Alta' },
      { problem: 'Muy pocas reseñas en Yelp (15) para validación ante nuevos clientes', impact: 'Nuevos clientes ven pocas reseñas y eligen competidores con más validación', priority: 'Alta' },
    ],
    quickActions: [
      'Crear sitio web básico con menú, horarios y enlace de pedido',
      'Activar perfil completo de Instagram con fotos del mofongo y oxtails',
      'Campaña para aumentar reseñas en Yelp a más de 50',
    ],
    growthActions: [
      'Implementar sistema de pedidos propio para reducir comisiones',
      'Estrategia de redes dirigida a la comunidad puertorriqueña de New Hampshire',
      'Añadir Uber Eats para completar cobertura de plataformas',
    ],
    strategicActions: [
      'Convertirse en el restaurante latino referente de Nashua y Manchester',
      'Construir comunidad digital de la diáspora puertorriqueña en NH',
      'Alcanzar 500+ reseñas en Google en 12 meses',
    ],
  },

  // ── Connecticut ───────────────────────────────────────────────────────────────

  {
    slug: 'coyote-flaco-hartford',
    name: 'Coyote Flaco',
    city: 'Hartford',
    state: 'CT',
    address: '635 New Britain Ave, Hartford, CT 06106',
    phone: '(860) 953-1299',
    cuisine: 'Mexicana',
    score: 58,
    googleScore: 72,
    webScore: 60,
    ordersScore: 35,
    socialScore: 55,
    seoScore: 65,
    googleRating: 4.3,
    googleReviews: 510,
    yelpRating: 4.0,
    yelpReviews: 195,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 2400,
    facebookFollowers: 3800,
    postsPerWeek: 3,
    strengths: [
      'Destacado por CTvisit.com como referente de cocina mexicana en Connecticut',
      'Más de 510 reseñas en Google — una de las más populares en Hartford',
      'Fuerte presencia en redes con más de 3,800 seguidores en Facebook',
    ],
    opportunities: [
      { problem: 'Sin presencia en ninguna plataforma de delivery', impact: 'Hartford tiene alta demanda de comida mexicana a domicilio completamente desatendida', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos online — solo walk-in y llamadas', impact: 'Pierde todos los clientes que buscan pedir desde su teléfono o computadora', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para su base de clientes establecida', impact: 'Con 510 reseñas en Google, tiene miles de clientes sin fidelizar', priority: 'Media' },
    ],
    quickActions: [
      'Registrarse en DoorDash y Uber Eats inmediatamente',
      'Activar sistema de pedidos online en el sitio web',
      'Implementar captura de emails en el restaurante y en línea',
    ],
    growthActions: [
      'Lanzar programa de lealtad "Amigos del Coyote" para clientes regulares',
      'Campaña de Google Ads para dominar búsquedas de "comida mexicana Hartford"',
      'Estrategia de contenido en TikTok mostrando los birria tacos y margaritas',
    ],
    strategicActions: [
      'Convertirse en el restaurante mexicano #1 de Hartford digitalmente',
      'Construir lista de 2,500+ clientes con email y SMS en 12 meses',
      'Expandir a segunda ubicación en West Hartford o New Britain',
    ],
  },

  // ── New York ──────────────────────────────────────────────────────────────────

  {
    slug: 'arepa-lady-jackson-heights',
    name: 'Arepa Lady',
    city: 'Jackson Heights',
    state: 'NY',
    address: '77-17 37th Ave, Jackson Heights, NY 11372',
    phone: '(917) 745-1111',
    cuisine: 'Colombiana',
    score: 71,
    googleScore: 80,
    webScore: 70,
    ordersScore: 55,
    socialScore: 70,
    seoScore: 82,
    googleRating: 4.5,
    googleReviews: 1250,
    yelpRating: 4.5,
    yelpReviews: 611,
    hasWebsite: true,
    websiteSpeed: 'Buena',
    mobileOptimized: true,
    hasOnlineOrdering: true,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 12000,
    facebookFollowers: 8500,
    postsPerWeek: 4,
    strengths: [
      'Más de 1,250 reseñas en Google y 611 en Yelp — una de las más reseñadas de Queens',
      '12,000 seguidores en Instagram — fuerte presencia de marca en redes sociales',
      'Historia icónica como carrito de comida que se convirtió en restaurante de culto',
    ],
    opportunities: [
      { problem: 'Sin presencia en DoorDash ni Uber Eats — invisible en apps de delivery', impact: 'Nueva York tiene millones de usuarios de delivery sin acceso a Arepa Lady', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar de su base masiva de seguidores', impact: 'Con 12,000 seguidores en Instagram, un programa de lealtad generaría visitas constantes', priority: 'Alta' },
      { problem: 'Sin captura de emails de clientes para marketing directo', impact: 'No puede comunicarse directamente con sus fans más allá de redes sociales', priority: 'Media' },
    ],
    quickActions: [
      'Activar DoorDash y Uber Eats para capturar el mercado de delivery de NYC',
      'Implementar captura de emails para convertir seguidores en clientes directos',
      'Lanzar programa de lealtad para los fans que visitan regularmente',
    ],
    growthActions: [
      'Campaña de email marketing mensual a la comunidad colombiana de NYC',
      'Usar los 12,000 seguidores de Instagram para promover el sistema de pedidos propio',
      'Expandir el catering para eventos de la comunidad latina en Queens y Manhattan',
    ],
    strategicActions: [
      'Convertir la historia icónica del carrito en una marca digital poderosa',
      'Abrir segunda ubicación en Manhattan o El Bronx aprovechando la reputación',
      'Construir lista de 5,000+ clientes con email y SMS para marketing directo',
    ],
  },

  {
    slug: 'la-boina-roja-jackson-heights',
    name: 'La Boina Roja',
    city: 'Jackson Heights',
    state: 'NY',
    address: '80-22 37th Ave, Jackson Heights, NY 11372',
    phone: '(718) 424-6711',
    cuisine: 'Colombiana',
    score: 51,
    googleScore: 70,
    webScore: 42,
    ordersScore: 30,
    socialScore: 45,
    seoScore: 65,
    googleRating: 4.2,
    googleReviews: 620,
    yelpRating: 4.0,
    yelpReviews: 180,
    hasWebsite: true,
    websiteSpeed: 'Lenta',
    mobileOptimized: false,
    hasOnlineOrdering: false,
    hasDoorDash: true,
    hasUberEats: false,
    hasGrubhub: false,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 980,
    facebookFollowers: 1600,
    postsPerWeek: 2,
    strengths: [
      'Steakhouse colombiano establecido desde 1998 — 27 años de trayectoria en Queens',
      'Más de 620 reseñas en Google — presencia sólida en el mercado de Jackson Heights',
      'Reconocido por NYC Tourism como destino gastronómico en Jackson Heights',
    ],
    opportunities: [
      { problem: 'Sitio web desactualizado y no optimizado para móviles', impact: 'La mayoría de clientes en NYC busca desde el teléfono y rebota al ver sitio lento', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio — solo DoorDash', impact: 'Paga ~$1,900/mes en comisiones que podrían ser ganancias directas', priority: 'Alta' },
      { problem: 'Sin presencia en Uber Eats ni Grubhub', impact: 'Jackson Heights tiene alta densidad de usuarios de múltiples plataformas', priority: 'Media' },
    ],
    quickActions: [
      'Rediseñar sitio web con optimización móvil y sistema de pedidos online',
      'Activar Uber Eats y Grubhub para maximizar visibilidad en NYC',
      'Crear contenido de Instagram mostrando los cortes de carne a la brasa colombiana',
    ],
    growthActions: [
      'Implementar sistema de pedidos propios para reducir comisiones',
      'Lanzar programa de lealtad celebrando los 27 años del restaurante',
      'Campaña de marketing dirigida a la comunidad colombiana de Queens y NJ',
    ],
    strategicActions: [
      'Modernizar la marca digital sin perder la identidad de 27 años',
      'Construir lista de 2,000+ clientes colombianos en NYC para marketing directo',
      'Posicionarse como el steakhouse colombiano referente de Nueva York',
    ],
  },

  // ── New Jersey ────────────────────────────────────────────────────────────────

  {
    slug: 'casa-vasca-newark',
    name: 'Casa Vasca',
    city: 'Newark',
    state: 'NJ',
    address: '141 Elm St, Newark, NJ 07105',
    phone: '(973) 465-1350',
    cuisine: 'Española',
    score: 59,
    googleScore: 82,
    webScore: 62,
    ordersScore: 28,
    socialScore: 45,
    seoScore: 78,
    googleRating: 4.5,
    googleReviews: 1200,
    yelpRating: 4.0,
    yelpReviews: 288,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 1800,
    facebookFollowers: 3200,
    postsPerWeek: 2,
    strengths: [
      'Institución del Ironbound desde 1976 — casi 50 años de trayectoria en Newark',
      'Más de 1,200 reseñas en Google con 4.5 estrellas — una de las más altas del área',
      'Rankeado como el #4 restaurante de Newark en TripAdvisor',
    ],
    opportunities: [
      { problem: 'Solo en Grubhub — ausente en DoorDash y Uber Eats', impact: 'Newark tiene alta demanda de delivery español; DoorDash y UberEats multiplican el alcance', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio en su sitio web', impact: 'Con 1,200 reseñas en Google, tiene miles de fans que podrían pedir directamente', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para casi 50 años de clientes', impact: 'La base de clientes más leal del Ironbound no tiene incentivo digital para regresar', priority: 'Media' },
    ],
    quickActions: [
      'Activar DoorDash y Uber Eats para completar presencia en plataformas',
      'Implementar sistema de pedidos propio en el sitio web',
      'Aumentar frecuencia de publicaciones en Instagram a 4-5 por semana',
    ],
    growthActions: [
      'Lanzar programa de lealtad "Club Vasca" para los 50 años del restaurante',
      'Campaña de email marketing a clientes existentes con menú estacional',
      'Estrategia de contenido celebrando los 50 años de historia en el Ironbound',
    ],
    strategicActions: [
      'Celebrar el 50 aniversario con campaña digital masiva en 2026',
      'Construir lista de 3,000+ clientes con email y SMS para marketing directo',
      'Posicionarse como el restaurante español más histórico del noreste de EE.UU.',
    ],
  },

  {
    slug: 'fornos-of-spain-newark',
    name: 'Fornos of Spain',
    city: 'Newark',
    state: 'NJ',
    address: '47 Ferry St, Newark, NJ 07105',
    phone: '(973) 589-4767',
    cuisine: 'Española',
    score: 62,
    googleScore: 80,
    webScore: 65,
    ordersScore: 30,
    socialScore: 55,
    seoScore: 82,
    googleRating: 4.4,
    googleReviews: 1520,
    yelpRating: 4.0,
    yelpReviews: 1165,
    hasWebsite: true,
    websiteSpeed: 'Regular',
    mobileOptimized: true,
    hasOnlineOrdering: false,
    hasDoorDash: false,
    hasUberEats: false,
    hasGrubhub: true,
    hasLoyaltyProgram: false,
    hasSmsCapture: false,
    hasEmailCapture: false,
    instagramFollowers: 3100,
    facebookFollowers: 5200,
    postsPerWeek: 3,
    strengths: [
      'Rankeado #2 en TripAdvisor entre los mejores restaurantes de Newark',
      'Más de 1,165 reseñas en Yelp y 1,520 en Google — reputación extraordinaria',
      'Institución del Ironbound desde 1980 con carta de vinos de más de 450 etiquetas españolas',
    ],
    opportunities: [
      { problem: 'Sin DoorDash ni Uber Eats — solo Grubhub para delivery', impact: 'Newark y el norte de NJ tienen millones de usuarios de DoorDash y Uber Eats sin acceso', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio a pesar de su enorme reputación digital', impact: 'Con 1,500+ reseñas en Google, podrían generar cientos de pedidos directos al mes', priority: 'Alta' },
      { problem: 'Sin programa de fidelización para 45 años de clientes', impact: 'La base de clientes más grande del Ironbound no tiene vínculo digital con el restaurante', priority: 'Media' },
    ],
    quickActions: [
      'Activar DoorDash y Uber Eats para capturar el mercado de delivery de NJ',
      'Implementar sistema de pedidos propios en el sitio web',
      'Activar captura de emails para los miles de clientes que ya los visitan',
    ],
    growthActions: [
      'Lanzar programa de lealtad "Club Fornos" para clientes VIP',
      'Campaña de email marketing mensual con especiales de vinos y paellas',
      'Uso del reconocimiento de TripAdvisor como herramienta de marketing digital',
    ],
    strategicActions: [
      'Convertirse en el restaurante español con mayor presencia digital del noreste',
      'Construir lista de 5,000+ clientes con email y SMS en 12 meses',
      'Usar los 45 años de historia para posicionarse como el referente culinario del Ironbound',
    ],
  },

  // ── Massachusetts (additional) ───────────────────────────────────────────────

  {
    slug: 'taino-restaurant-holyoke',
    name: 'Taino Restaurant',
    city: 'Holyoke',
    state: 'MA',
    address: '548 South St, Holyoke, MA 01040',
    phone: '(413) 322-8151',
    cuisine: 'Puertorriqueña',
    score: 38,
    googleScore: 65, webScore: 40, ordersScore: 30, socialScore: 35, seoScore: 42,
    googleRating: 4.3, googleReviews: 180, yelpRating: 4.0, yelpReviews: 45,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: false, hasGrubhub: true,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 620, facebookFollowers: 1100, postsPerWeek: 1,
    strengths: [
      'Auténtica cocina puertorriqueña en una ciudad con alta comunidad latina',
      'Tiene sistema de pedidos online propio y presencia en Grubhub',
      'Calificación sólida de 4.3 en Google con clientela local fiel',
    ],
    opportunities: [
      { problem: 'Sin DoorDash ni Uber Eats — ausente en las apps más populares', impact: 'Holyoke tiene alta población latina que usa delivery constantemente', priority: 'Alta' },
      { problem: 'Redes sociales muy poco activas para el mercado local', impact: 'La comunidad puertorriqueña de Holyoke es muy activa en redes', priority: 'Alta' },
      { problem: 'Sin programa de lealtad ni captura de clientes', impact: 'No convierte visitas en clientes recurrentes de forma sistemática', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats', 'Crear contenido semanal en Instagram para la comunidad boricua', 'Optimizar Google Business con fotos actualizadas'],
    growthActions: ['Lanzar programa de lealtad "Taino Club"', 'Campaña de SMS marketing para clientes existentes', 'Expandir catering para eventos de la comunidad latina de Holyoke'],
    strategicActions: ['Posicionarse como el restaurante puertorriqueño referente del oeste de MA', 'Construir lista de 1,000+ clientes con email y SMS', 'Expandir horario con comunicación digital activa'],
  },

  {
    slug: 'el-rincon-boricua-holyoke',
    name: 'El Rincón Boricua',
    city: 'Holyoke',
    state: 'MA',
    address: '216 Lyman St, Holyoke, MA 01040',
    phone: '(413) 534-1011',
    cuisine: 'Puertorriqueña',
    score: 32,
    googleScore: 70, webScore: 15, ordersScore: 20, socialScore: 22, seoScore: 35,
    googleRating: 4.6, googleReviews: 140, yelpRating: 4.5, yelpReviews: 39,
    hasWebsite: false, websiteSpeed: 'Lenta', mobileOptimized: false,
    hasOnlineOrdering: false, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 280, facebookFollowers: 540, postsPerWeek: 1,
    strengths: [
      'Calificación de 4.6 en Google — excelencia culinaria reconocida localmente',
      'Rankeado #9 de 62 restaurantes en Holyoke en TripAdvisor',
      'Reconocido por el mofongo y pernil auténticos con porciones generosas',
    ],
    opportunities: [
      { problem: 'Sin sitio web ni presencia en plataformas de delivery', impact: 'Completamente invisible para clientes que buscan online', priority: 'Alta' },
      { problem: 'Sin ninguna plataforma de delivery — solo come en persona', impact: 'Pierde todo el mercado de pedidos a domicilio', priority: 'Alta' },
      { problem: 'Redes sociales mínimas a pesar de calidad excepcional', impact: 'No capitaliza su excelente reputación para crecer', priority: 'Alta' },
    ],
    quickActions: ['Crear sitio web básico con menú y pedidos', 'Registrarse en DoorDash inmediatamente', 'Activar Instagram con fotos del mofongo y pernil'],
    growthActions: ['Implementar sistema de pedidos propio', 'Estrategia de redes para la comunidad boricua de Holyoke y Springfield', 'Campaña para aumentar reseñas en Yelp a 150+'],
    strategicActions: ['Construir presencia digital completa aprovechando la calidad ya reconocida', 'Alcanzar 500+ reseñas en Google en 12 meses', 'Expandir a segunda ubicación en Springfield'],
  },

  {
    slug: 'el-potro-chelsea',
    name: 'El Potro Mexican Grill',
    city: 'Chelsea',
    state: 'MA',
    address: '170 Everett Ave, Chelsea, MA 02150',
    phone: '(617) 466-0007',
    cuisine: 'Mexicana',
    score: 55,
    googleScore: 68, webScore: 62, ordersScore: 42, socialScore: 52, seoScore: 58,
    googleRating: 4.2, googleReviews: 340, yelpRating: 4.0, yelpReviews: 167,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1800, facebookFollowers: 2600, postsPerWeek: 2,
    strengths: [
      'Parte de una cadena de 4 ubicaciones en MA — marca establecida regionalmente',
      'Tiene sistema de pedidos propio — sin comisiones de apps externas',
      'Horario extendido hasta la 1am — único en el mercado de Chelsea',
    ],
    opportunities: [
      { problem: 'Sin DoorDash ni Uber Eats — invisible en apps de delivery populares', impact: 'Chelsea tiene alta densidad de usuarios de delivery apps', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar de múltiples ubicaciones', impact: 'Un programa cruzado entre las 4 ubicaciones multiplicaría clientes recurrentes', priority: 'Alta' },
      { problem: 'Sin captura de SMS o email de clientes', impact: 'No puede comunicarse directamente con su base de clientes', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats en la ubicación de Chelsea', 'Implementar captura de email/SMS en sistema de pedidos', 'Crear programa de lealtad unificado para las 4 ubicaciones'],
    growthActions: ['Campaña de redes dirigida a la comunidad mexicana de Chelsea y East Boston', 'Lanzar "Club El Potro" con descuentos para clientes frecuentes', 'Estrategia de contenido mostrando las recetas familiares auténticas'],
    strategicActions: ['Convertir las 4 ubicaciones en una marca digital cohesiva', 'Construir lista de 3,000+ clientes compartida entre ubicaciones', 'Expandir a quinta ubicación en Everett o Revere'],
  },

  {
    slug: 'el-potro-lowell',
    name: 'El Potro Mexican Grill',
    city: 'Lowell',
    state: 'MA',
    address: '124 Merrimack St, Lowell, MA 01852',
    phone: '(978) 455-2840',
    cuisine: 'Mexicana',
    score: 58,
    googleScore: 70, webScore: 62, ordersScore: 45, socialScore: 55, seoScore: 58,
    googleRating: 4.3, googleReviews: 410, yelpRating: 4.0, yelpReviews: 403,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 2100, facebookFollowers: 3100, postsPerWeek: 2,
    strengths: [
      'La ubicación más reseñada de la cadena — 403 reseñas en Yelp y 410 en Google',
      'Ganador del premio "Best of Lowell" — reconocimiento oficial de la ciudad',
      'Amplio espacio con terraza exterior — ideal para familias grandes',
    ],
    opportunities: [
      { problem: 'Sin presencia en DoorDash ni Uber Eats en Lowell', impact: 'Lowell tiene 115,000 habitantes con alta demanda de delivery latino', priority: 'Alta' },
      { problem: 'Sin captura de datos de clientes a pesar de ser el #1 en Lowell', impact: 'Miles de clientes sin datos = imposible hacer marketing directo', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para una ubicación tan popular', impact: 'La ubicación más visitada de la cadena necesita un programa VIP', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats en Lowell', 'Implementar captura de email en el punto de venta', 'Usar el premio "Best of Lowell" como contenido de marketing'],
    growthActions: ['Lanzar programa de lealtad exclusivo para Lowell', 'Campaña de Google Ads dominando búsquedas de "mexicano Lowell"', 'Estrategia de contenido en TikTok con el equipo de cocina'],
    strategicActions: ['Convertir el #1 de Lowell en referente digital del noreste de MA', 'Construir lista de 2,500+ clientes para marketing directo', 'Capitalizar el "Best of Lowell" para expansión a otras ciudades'],
  },

  {
    slug: 'sazon-latino-worcester',
    name: 'Sazón Latino Restaurant',
    city: 'Worcester',
    state: 'MA',
    address: '130 Chandler St, Worcester, MA 01610',
    phone: '(508) 797-5645',
    cuisine: 'Dominicana / Puertorriqueña',
    score: 48,
    googleScore: 68, webScore: 55, ordersScore: 42, socialScore: 42, seoScore: 48,
    googleRating: 4.3, googleReviews: 250, yelpRating: 4.0, yelpReviews: 65,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: false, hasDoorDash: true, hasUberEats: true, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 950, facebookFollowers: 1600, postsPerWeek: 2,
    strengths: [
      'Negocio familiar dominicano establecido desde 2001 — más de 23 años de tradición',
      'Disponible en DoorDash y Uber Eats — buena cobertura de delivery',
      'Reconocido por porciones generosas de comida casera dominicana y puertorriqueña',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio — paga comisiones en dos plataformas', impact: 'Aproximadamente $1,900/mes en comisiones de DoorDash y Uber Eats', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para 23 años de clientes fieles', impact: 'Una base establecida sin ningún incentivo para regresar regularmente', priority: 'Alta' },
      { problem: 'Presencia social limitada para el potencial del restaurante', impact: 'Worcester tiene 200,000+ habitantes con gran comunidad latina subestimada', priority: 'Media' },
    ],
    quickActions: ['Implementar sistema de pedidos propio para reducir comisiones', 'Activar captura de email en el restaurante', 'Aumentar frecuencia en Instagram a 4 posts semanales'],
    growthActions: ['Lanzar "Sazón Club" — programa de lealtad para clientes frecuentes', 'Campaña de email marketing semanal con especiales del día', 'Estrategia de contenido para la comunidad dominicana y puertorriqueña de Worcester'],
    strategicActions: ['Posicionarse como el mejor dominicano-puertorriqueño de Worcester', 'Construir lista de 1,500+ clientes para marketing directo', 'Reducir comisiones de apps al 40% con canal de pedidos propio'],
  },

  {
    slug: 'casa-verde-scituate',
    name: 'Casa Verde Latin Kitchen',
    city: 'Scituate',
    state: 'MA',
    address: '108 Front St, Scituate, MA 02066',
    phone: '(781) 378-2037',
    cuisine: 'Latinoamericana',
    score: 52,
    googleScore: 68, webScore: 60, ordersScore: 38, socialScore: 48, seoScore: 50,
    googleRating: 4.3, googleReviews: 190, yelpRating: 4.0, yelpReviews: 55,
    hasWebsite: true, websiteSpeed: 'Buena', mobileOptimized: true,
    hasOnlineOrdering: false, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1100, facebookFollowers: 1400, postsPerWeek: 2,
    strengths: [
      'Único restaurante de cocina latinoamericana en Scituate Harbor — nicho exclusivo',
      'Cocina de alta calidad con ingredientes frescos y menú creativo',
      'Sitio web bien diseñado con buena velocidad de carga',
    ],
    opportunities: [
      { problem: 'Sin presencia en ninguna plataforma de delivery', impact: 'Los suburbios del sur de Boston tienen alta demanda de delivery premium', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio para takeout', impact: 'Clientes del área no pueden ordenar sin llamar por teléfono', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para clientes del vecindario', impact: 'Scituate es una comunidad pequeña donde la fidelización es clave', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash para el área de Scituate y Marshfield', 'Implementar sistema de pedidos online (Toast o Square)', 'Crear campaña de Instagram para la comunidad local'],
    growthActions: ['Lanzar programa de lealtad para clientes del vecindario', 'Expandir catering para eventos y bodas en el área del puerto', 'Campaña de email marketing mensual a clientes locales'],
    strategicActions: ['Posicionarse como el destino gastronómico latino del South Shore', 'Construir lista de 800+ clientes para marketing directo', 'Expandir a segunda ubicación en Cohasset o Duxbury'],
  },

  // ── Rhode Island (additional) ─────────────────────────────────────────────────

  {
    slug: 'cielito-mexican-kitchen-providence',
    name: 'Cielito Mexican Kitchen',
    city: 'Providence',
    state: 'RI',
    address: '186 Union St, Providence, RI 02903',
    phone: '(401) 563-7026',
    cuisine: 'Mexicana',
    score: 54,
    googleScore: 60, webScore: 62, ordersScore: 48, socialScore: 48, seoScore: 55,
    googleRating: 4.2, googleReviews: 155, yelpRating: 4.0, yelpReviews: 50,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1800, facebookFollowers: 1200, postsPerWeek: 3,
    strengths: [
      'Abierto por el chef Diego Alcantar, también dueño del aclamado Tuxpan Taqueria',
      'Destacado en Boston Globe — reconocimiento mediático regional significativo',
      'Tiene sistema de pedidos propio a través de Toast — sin comisiones de apps',
    ],
    opportunities: [
      { problem: 'Sin DoorDash ni Uber Eats — pierde clientes que descubren en apps', impact: 'Providence tiene alta densidad de usuarios de delivery universitarios', priority: 'Alta' },
      { problem: 'Solo 50 reseñas en Yelp para un restaurante de esta calidad', impact: 'Necesita más reseñas para aparecer en las búsquedas de Yelp', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para construir base de clientes recurrentes', impact: 'Restaurante relativamente nuevo que necesita fidelizar desde el inicio', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash para llegar a estudiantes universitarios de Providence', 'Campaña para aumentar reseñas en Yelp a 150+', 'Usar la conexión con Tuxpan para campañas de marketing cruzado'],
    growthActions: ['Lanzar programa de lealtad desde el inicio para crear base sólida', 'Campaña de Instagram mostrando la cocina michoacana auténtica', 'Colaborar con influencers de comida de Providence'],
    strategicActions: ['Construir marca complementaria a Tuxpan en el mercado de RI', 'Posicionarse como referente de cocina mexicana fina en Providence', 'Alcanzar 500+ reseñas en Google en 12 meses'],
  },

  // ── Connecticut (additional) ──────────────────────────────────────────────────

  {
    slug: 'brasitas-stamford',
    name: 'Brasitas',
    city: 'Stamford',
    state: 'CT',
    address: '954 E Main St, Stamford, CT 06902',
    phone: '(203) 323-3176',
    cuisine: 'Nuevo Latino',
    score: 62,
    googleScore: 72, webScore: 65, ordersScore: 45, socialScore: 60, seoScore: 68,
    googleRating: 4.3, googleReviews: 620, yelpRating: 4.0, yelpReviews: 374,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: false, hasDoorDash: true, hasUberEats: true, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 3200, facebookFollowers: 4100, postsPerWeek: 3,
    strengths: [
      'Pionero del Nuevo Latino en CT desde 1998 — más de 25 años de trayectoria',
      'Dos ubicaciones (Stamford y Norwalk) — presencia regional consolidada',
      'Más de 600 reseñas en Google con 4.3 estrellas — reputación muy establecida',
    ],
    opportunities: [
      { problem: 'Sin sistema de pedidos propio — paga comisiones en DoorDash y Uber Eats', impact: 'Con dos ubicaciones, las comisiones combinadas superan $3,800/mes', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para 25 años de clientes', impact: 'Base masiva de clientes sin ningún vínculo digital con el restaurante', priority: 'Alta' },
      { problem: 'Sin captura de emails para marketing directo', impact: 'No puede comunicarse con sus miles de clientes entre visitas', priority: 'Media' },
    ],
    quickActions: ['Implementar sistema de pedidos propio para reducir comisiones', 'Activar captura de email en ambas ubicaciones', 'Lanzar programa de lealtad unificado para Stamford y Norwalk'],
    growthActions: ['Campaña de email marketing mensual a clientes registrados', 'Reducir presencia pagada en apps redirigiendo a canal propio', 'Estrategia de contenido celebrando los 25 años del restaurante'],
    strategicActions: ['Recuperar $3,800/mes en comisiones con canal propio', 'Construir lista de 4,000+ clientes entre ambas ubicaciones', 'Expandir a tercera ubicación en Greenwich o Westport'],
  },

  {
    slug: 'el-rinconcito-peruano-hartford',
    name: 'Rinconcito Peruano',
    city: 'Hartford',
    state: 'CT',
    address: '391 Main St, Hartford, CT 06106',
    phone: '(860) 254-8264',
    cuisine: 'Peruana',
    score: 55,
    googleScore: 70, webScore: 60, ordersScore: 48, socialScore: 48, seoScore: 55,
    googleRating: 4.4, googleReviews: 320, yelpRating: 4.0, yelpReviews: 85,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: true, hasGrubhub: true,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1400, facebookFollowers: 1900, postsPerWeek: 2,
    strengths: [
      '15 años de servicio — el restaurante peruano más antiguo y establecido de Hartford',
      'Tiene sistema de pedidos propio además de Uber Eats y Grubhub',
      'Calificación de 4.4 en Google — excelente reputación culinaria local',
    ],
    opportunities: [
      { problem: 'Sin DoorDash — la plataforma más usada en Hartford', impact: 'DoorDash domina el mercado de delivery en Hartford sobre Uber Eats', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar de 15 años de clientes', impact: 'Una base fiel de 15 años sin ningún programa de fidelización digital', priority: 'Alta' },
      { problem: 'Sin captura de datos de clientes para marketing', impact: 'No puede reactivar clientes inactivos ni hacer campañas directas', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash para completar cobertura de plataformas', 'Implementar captura de email en sistema de pedidos online', 'Crear contenido de Instagram mostrando el ceviche y lomo saltado'],
    growthActions: ['Lanzar programa de lealtad celebrando 15 años de servicio', 'Campaña de email marketing para la comunidad peruana de Connecticut', 'Estrategia de TikTok mostrando la preparación de platos peruanos'],
    strategicActions: ['Posicionarse como el restaurante peruano #1 de Connecticut', 'Construir lista de 1,500+ clientes para marketing directo', 'Expandir a New Haven o Bridgeport para cubrir todo CT'],
  },

  {
    slug: 'banana-brazil-hartford',
    name: 'Banana Brazil Grill',
    city: 'Hartford',
    state: 'CT',
    address: '341 New Park Ave, Hartford, CT 06106',
    phone: '(860) 206-9188',
    cuisine: 'Brasileña',
    score: 50,
    googleScore: 65, webScore: 55, ordersScore: 35, socialScore: 48, seoScore: 50,
    googleRating: 4.2, googleReviews: 280, yelpRating: 4.0, yelpReviews: 104,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: false, hasDoorDash: false, hasUberEats: false, hasGrubhub: true,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1600, facebookFollowers: 3200, postsPerWeek: 2,
    strengths: [
      'Buffet brasileño de churrasco — concepto único en Hartford, CT',
      'Más de 38 platos de carne BBQ estilo churrasco — experiencia gastronómica diferenciada',
      '100% recomendado en Facebook con 391 reseñas — base de clientes muy leal',
    ],
    opportunities: [
      { problem: 'Solo en Grubhub — ausente en DoorDash y Uber Eats', impact: 'Hartford tiene alta demanda de delivery que va a la competencia', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio para takeout del buffet', impact: 'El buffet de churrasco se presta perfectamente para pedidos de grupo y catering', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para fidelizar clientes del buffet', impact: 'Los clientes del buffet visitan con alta frecuencia sin incentivo digital', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats con un menú adaptado para delivery', 'Implementar sistema de reservas online para el buffet', 'Crear paquetes de catering visibles en el sitio web'],
    growthActions: ['Lanzar programa de lealtad "Churrasco Club" con visitas frecuentes', 'Estrategia de contenido mostrando la experiencia del buffet en video', 'Campaña de catering para empresas y eventos en Hartford'],
    strategicActions: ['Expandir el concepto de churrasco a New Haven o Springfield', 'Construir lista de 2,000+ clientes para marketing directo', 'Posicionarse como el destino de catering brasileño de Connecticut'],
  },

  {
    slug: 'chacra-pisco-bar-new-haven',
    name: 'Chacra Pisco Bar',
    city: 'New Haven',
    state: 'CT',
    address: '152 Temple St, New Haven, CT 06510',
    phone: '(203) 714-1771',
    cuisine: 'Peruana',
    score: 62,
    googleScore: 72, webScore: 62, ordersScore: 52, socialScore: 62, seoScore: 68,
    googleRating: 4.4, googleReviews: 380, yelpRating: 4.5, yelpReviews: 120,
    hasWebsite: true, websiteSpeed: 'Buena', mobileOptimized: true,
    hasOnlineOrdering: true, hasDoorDash: false, hasUberEats: false, hasGrubhub: false,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: true,
    instagramFollowers: 3800, facebookFollowers: 2900, postsPerWeek: 4,
    strengths: [
      'Mejor Restaurante Latino de CT 2024 según Connecticut Magazine',
      'Mejor Ceviche, Mejor Peruana y Mejor Brunch en New Haven County 2024',
      'Captura de emails activa y presencia fuerte en Instagram con 3,800 seguidores',
    ],
    opportunities: [
      { problem: 'Sin presencia en DoorDash ni Uber Eats', impact: 'New Haven tiene alta población universitaria que usa delivery constantemente', priority: 'Alta' },
      { problem: 'Sin programa de lealtad a pesar de múltiples premios estatales', impact: 'Los ganadores de "Best of CT" necesitan capitalizar su reputación para retener clientes', priority: 'Alta' },
      { problem: 'Sin SMS marketing para comunicarse directamente con clientes', impact: 'Solo captura email — el SMS tiene tasas de apertura 4x más altas', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats para alcanzar el mercado universitario de Yale', 'Implementar captura de SMS además del email ya activo', 'Usar los premios de CT Magazine como contenido de marketing'],
    growthActions: ['Lanzar programa de lealtad aprovechando la reputación de "Best of CT"', 'Campaña de email marketing mensual con menús de temporada', 'Colaborar con hoteles y concierges de New Haven para recomendaciones'],
    strategicActions: ['Convertirse en el restaurante peruano de referencia nacional de New England', 'Expandir a segunda ubicación en Stamford o Greenwich', 'Construir lista de 3,000+ clientes para marketing directo'],
  },

  {
    slug: 'rubamba-new-haven',
    name: 'Rubamba Restaurant',
    city: 'New Haven',
    state: 'CT',
    address: '25 High St, New Haven, CT 06510',
    phone: '(203) 773-0032',
    cuisine: 'Fusión Latina',
    score: 48,
    googleScore: 62, webScore: 58, ordersScore: 35, socialScore: 45, seoScore: 50,
    googleRating: 4.1, googleReviews: 240, yelpRating: 4.0, yelpReviews: 95,
    hasWebsite: true, websiteSpeed: 'Regular', mobileOptimized: true,
    hasOnlineOrdering: false, hasDoorDash: false, hasUberEats: false, hasGrubhub: true,
    hasLoyaltyProgram: false, hasSmsCapture: false, hasEmailCapture: false,
    instagramFollowers: 1200, facebookFollowers: 1800, postsPerWeek: 2,
    strengths: [
      'Ubicado a pasos de Yale University — acceso a comunidad universitaria densa',
      'Cocina de fusión colombiana y latina — menú creativo diferenciado',
      'Rankeado #87 de 317 restaurantes en New Haven en TripAdvisor',
    ],
    opportunities: [
      { problem: 'Solo en Grubhub — ausente en DoorDash y Uber Eats', impact: 'Los estudiantes de Yale son usuarios intensivos de DoorDash y Uber Eats', priority: 'Alta' },
      { problem: 'Sin sistema de pedidos propio para takeout', impact: 'La ubicación junto a Yale exige tener pedidos online simples y rápidos', priority: 'Alta' },
      { problem: 'Sin programa de lealtad para la comunidad universitaria', impact: 'Los estudiantes son clientes ideales para programas de lealtad con descuentos', priority: 'Media' },
    ],
    quickActions: ['Activar DoorDash y Uber Eats para el mercado universitario', 'Implementar sistema de pedidos online rápido para el lunch', 'Crear descuentos especiales para estudiantes y profesores de Yale'],
    growthActions: ['Lanzar programa de lealtad para la comunidad de Yale', 'Campaña de redes para los 15,000+ estudiantes de Yale', 'Estrategia de contenido mostrando los platos de fusión colombiana'],
    strategicActions: ['Posicionarse como el restaurante latino favorito del campus de Yale', 'Construir lista de 1,500+ clientes universitarios para marketing', 'Expandir catering para eventos académicos y universitarios'],
  },
];

export function getRestaurant(slug: string): Restaurant | undefined {
  return restaurants.find(r => r.slug === slug);
}

export function getScoreColor(score: number): string {
  if (score >= 70) return 'text-emerald-600';
  if (score >= 50) return 'text-amber-600';
  return 'text-red-600';
}

export function getScoreBg(score: number): string {
  if (score >= 70) return 'bg-emerald-50 border-emerald-200';
  if (score >= 50) return 'bg-amber-50 border-amber-200';
  return 'bg-red-50 border-red-200';
}

export function getScoreLabel(score: number): string {
  if (score >= 70) return 'Avanzado';
  if (score >= 50) return 'En Desarrollo';
  if (score >= 30) return 'Crítico';
  return 'Urgente';
}
